### ISSUE TITLE
GraphView 제작

### ISSUE THREAD

**Issue by sero3779** [sero3779/ios-wanted-GyroData#1]
## Description
MotionRecording 화면과 MotionReplay 화면에서 공용으로 사용될 GraphView를 제작하는 commit들이 담길 issue입니다.

## Todo
- [x] 눈금 격자 만들기
- [x] x, y, z 정보 기반으로 그래프 생성하는 로직 제작
- [x] x, y, z 현재값 표시하기
- [x] 업스케일링 시 이전 그래프 일괄적으로 스케일 조절하는 로직 제작

## Screenshot
<img width="314" alt="image" src="https://user-images.githubusercontent.com/67148595/209544439-ef137735-ecf9-48f5-80ef-561bca2a912e.png">
